### ISSUE TITLE
Release Dates

### ISSUE THREAD

**Issue by bm-1961** [MajesticKhan/Nowcasting-Python#6]
Hey,

I dont know if this is an issue with how I am formatting data or something else, but I am trying to run the code on dataframes which have different release dates.

As a result I have formatted the data in a weekly format with NAs in between.

When I run this code i then either get the error:

ValueError: expected square matrix

or 

ValueError: Internal work array size computation failed: -5

Ideally I would also be able to run with actual weekly data as an input.

Have attached the relevant files and would love any thoughts you have?
[Spec_US_example.xlsx](https://github.com/MajesticKhan/Nowcasting-Python/files/5939812/Spec_US_example.xlsx)

[2016-06-29.xlsx](https://github.com/MajesticKhan/Nowcasting-Python/files/5939824/2016-06-29.xlsx)

**Comment by MajesticKhan** [comment]
Hey there!

First thing, make sure the frequency type is lowercase, so "Q" should be "q".
second, the error is caused by https://github.com/MajesticKhan/Nowcasting-Python/blob/7b082e4997e9769be29baaa345f1de2951f3247a/Functions/dfm.py#L276 

where np.cov is returning a scalar value instead of a square matrix (this is due to the blocking structure where there is only one value set to 1 on column 2).

The third thing is that the code is based on monthly and quarterly data.

**Comment by MajesticKhan** [comment]
@bm-1961 FYI, the reason why I didn't go further into adapting the model to handle various frequencies is because my focus was converting it to python

**Comment by bm-1961** [comment]
Ah ok thanks so much.

I am a little confused by setting the number to 1 in the columns - is there an expected minimum amount for each?

Also, regarding the dates (since the code seems to accept NA's), I could presumably just reformat my dataframe with made up dates which go up in increments of months even though the data is actually weekly. Then once the model has run I could reapply the correct weights.

**Comment by bm-1961** [comment]
I wondered if I might ask another favour.

Is there a simple way to alter the code so that the quarterly input can have s 3 NaN's between data points rather than 2?
